###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
mhdgc-redis:
  image: redis:alpine
  container_name: mhdgc-redis

mhdgc-mysql:
  image: mysql:5.7
  container_name: mhdgc-mysql
  volumes:
      - ../data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
  ports:
    - "8106:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}

mhdgc-nginx:
  image: phpdockerio/nginx:latest
  container_name: mhdgc-nginx
  volumes:
      - ../www:/var/www/mhdgc
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "80:80"
  links:
   - mhdgc-php-fpm
   - mhdgc-redis

mhdgc-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: mhdgc-php-fpm
  volumes:
    - ../www:/var/www/mhdgc
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - mhdgc-mysql
    - mhdgc-redis
